version: '3'
services:
    presentation:
        build:
            context:  ./
            dockerfile: Dockerfile
        ports:
            - 1947:1947
        env_file: 
            - presentation.env
        volumes:
            - .:/usr/src/presentation
        container_name: presentation
    
    spotify:
        build:
            context:  ./spotify-widget
            dockerfile: Dockerfile
        env_file: 
            - spotify.env
        ports:
            - 3000:3000
        container_name: spotify

volumes:
    data:
        driver: local