version: '3'
services:
    presentation:
        build:
            context:  ./
            dockerfile: Dockerfile
        ports:
            - 1947:1947
        env_file: 
            - presentation.env
        volumes:
            - .:/usr/src/presentation
            - /usr/src/presentation/spotify-widget
        container_name: presentation
    
    spotify:
        build:
            context:  ./spotify-widget
            dockerfile: Dockerfile
        env_file: 
            - spotify.env
        ports:
            - 3000:3000
        volumes:
            - ./spotify-widget:/usr/src/spotify-widget
            - /usr/src/spotify-widget/node_modules
        container_name: spotify