import {
  mdiArrowUpBoldHexagonOutline,
  mdiLogout,
  mdiLoginVariant,
  mdiLogin,
  mdiClose,
  mdiVolumeOff,
  mdiVolumeHigh,
  mdiSubtitles,
  mdiTeach,
  mdiTransition,
  mdiMenu,
  mdiArrowDownBoldHexagonOutline,
  mdiPlusCircle,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
  mdiDesktopTowerMonitor,
  mdiDelete,
  mdiSpotify,
} from "@mdi/js";

const mdi42 =
  "M9 17v-2H1v-3l4-4 4-4h4L9 8l-4 4h8v7H9v-2zM15 14v-2l2-2 2-2V4h4v4l-2 2-2 2v4h-4v-2zM21 14l2-2v4h-4l2-2zM15 6V4h4l-2 2-2 2V6z";

export default {
  mdiArrowUpBoldHexagonOutline,
  mdiLogout,
  mdiLogin,
  mdiLoginVariant,
  mdiClose,
  mdiVolumeOff,
  mdiVolumeHigh,
  mdiSubtitles,
  mdiTeach,
  mdiTransition,
  mdiMenu,
  mdiArrowDownBoldHexagonOutline,
  mdiPlusCircle,
  mdiWeatherNight,
  mdiWhiteBalanceSunny,
  mdiDesktopTowerMonitor,
  mdiDelete,
  mdiSpotify,
  mdi42,
};
